### PR TITLE
Add tasklist to GitHub markdown

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**

### CODE REVIEW

**Comment by mbarkhau** [comment]
Thanks for this PR, would you like to also add a test for this?

**Comment by Andrew-Chen-Wang** [comment]
Just created a separate test case to make sure the extension was working as expected. Not sure if that's enough?

**Comment by mbarkhau** [comment]
Thanks for the PR, lgtm. :+1:

**Comment by mbarkhau** [comment]
Available now on PyPI: https://pypi.org/project/cmarkgfm/0.5.2/

**Comment by Andrew-Chen-Wang** [comment]
Thank you!

**Pull request merged**
