### PR TITLE
Add GitHub Actions

### LINKED ISSUE #22: Wheel Build Automation
If it's not too much trouble, could you build and upload wheels for Python 3.8 to pypi. For now I guess I'll have to add gcc to my docker image.

### PR DESCRIPTION
**Pull request by mbarkhau**
Fixes #22 

Status
- [x] : Test and Lint
- [x] : Linux Wheels
- [x] : MacOS Wheels
- [x] : Windows Wheels

Haven't looked too much into it yet, but I'll see if I can get MacOS and Windows working with the [multibuild repository](https://github.com/theacodes/cmarkgfm-wheels) (possibly also replace the existing manylinux stage if it makes things more simple).

### CODE REVIEW

**Comment by fruch** [comment]
Looks like a good direction, i.e. keeping it in the same repo and using github actions.

I think this multibuild might be a bit of a deadend, and maybe was a nice a idea.

But I think cibuildwheel is a bit more clean solution 
https://cibuildwheel.readthedocs.io/en/stable/setup/#github-actions

I was using it ontop of Travis.CI, and lot of the know how on how to build wheels correctly in multiple os and multiple python version is embedded into that project.

Here is how I used it:
https://github.com/scylladb/python-driver/blob/master/.travis.yml

**Comment by fruch** [comment]
@mbarkhau 
Here it's running now with my fork
https://github.com/fruch/cmarkgfm/actions/runs/379797456

**Comment by mbarkhau** [comment]
Very cool, I'll check it out tomorrow.

**Comment by mbarkhau** [comment]
@theacodes I think this is ready for review whenever you have time.

**Comment by mbarkhau** [comment]
Unfortunately, I can't test the upload itself, if there is any issue, this may be of help: https://github.com/joerick/cibuildwheel/blob/master/examples/github-deploy.yml

**Pull request merged**
